@baseUrl = http://localhost:3000

### 1. Get all contacts
GET {{baseUrl}}/contacts

### 2. Create a test contact
# @name createContact
POST {{baseUrl}}/contacts
Content-Type: application/json

{
  "firstName": "David",
  "lastName": "Canales",
  "email": "david@example.com",
  "favoriteColor": "Blue",
  "birthday": "January 1, 2000"
}

### Save the new contact ID
@contactId = {{createContact.response.body.$.id}}

### 3. Get the new contact
GET {{baseUrl}}/contacts/{{contactId}}

### 4. Update the contact
PUT {{baseUrl}}/contacts/{{contactId}}
Content-Type: application/json

{
  "firstName": "David",
  "lastName": "Canales Mejia",
  "email": "david.updated@example.com",
  "favoriteColor": "Green",
  "birthday": "January 1, 2000"
}

### 5. Delete the contact
DELETE {{baseUrl}}/contacts/{{contactId}}